---
- hosts: all
  tasks:
    - name: create deployment folders
      command: mkdir -p /home/ubuntu/deploy-webwar/deploymentconfig
      ignore_errors: True

    - name: copy webappwar
      copy:
        src: /home/ubuntu/deploy-webwar/deploymentconfig/target
        dest: /home/ubuntu/deploy-webwar/deploymentconfig/

    - name: copy webappwar Dockerfile
      copy:
        src: /home/ubuntu/deploy-webwar/deploymentconfig/Dockerfile
        dest: /home/ubuntu/deploy-webwar/deploymentconfig/

    - name: copy webappwar docker-compose yml
      copy:
        src: /home/ubuntu/deploy-webwar/deploymentconfig/webappwar-docker-compose.yml
        dest: /home/ubuntu/deploy-webwar/deploymentconfig/

    - name: copy webappwar settings .env file
      copy:
        src: /home/ubuntu/deploy-webwar/deploymentconfig/webappwar.settings.qa.env
        dest: /home/ubuntu/deploy-webwar/deploymentconfig/

    - name: stop running webappwar container
      command: sudo docker container stop webappwar
      ignore_errors: True
    
    - name: remove existing webappwar container
      command: sudo docker container rm webappwar
      ignore_errors: True

    - name: remove existing webappwar image
      command: sudo docker rmi webappwar --force
      ignore_errors: True

    - name: build image of webappwar using the dockerfile in this path
      command: sudo docker image build -t webappwar /home/ubuntu/deploy-webwar/deploymentconfig

    - name: docker-compose-up webappwar
      command: sudo docker-compose --env-file /home/ubuntu/deploy-webwar/deploymentconfig/webappwar.settings.qa.env -f /home/ubuntu/deploy-webwar/deploymentconfig/webappwar-docker-compose.yml up -d